-- MySQL Script generated by MySQL Workbench
-- Sun Oct 10 01:47:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Publicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Publicacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Publicacion` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha_creacion` DATE NULL,
  PRIMARY KEY (`id_publicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fecha_inscripcion` DATE NULL,
  `activo` TINYINT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Intercambio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Intercambio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Intercambio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_concretado` TINYINT NULL,
  `fecha_intercambio` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mensaje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mensaje` (
  `id_mensaje` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `Intercambio_id` INT NOT NULL,
  `Publicaciones_id_publicacion` INT NOT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `fk_Mensaje_Intercambio1_idx` (`Intercambio_id` ASC) VISIBLE,
  INDEX `fk_Mensaje_Publicaciones1_idx` (`Publicaciones_id_publicacion` ASC) VISIBLE,
  CONSTRAINT `fk_Mensaje_Intercambio1`
    FOREIGN KEY (`Intercambio_id`)
    REFERENCES `mydb`.`Intercambio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensaje_Publicaciones1`
    FOREIGN KEY (`Publicaciones_id_publicacion`)
    REFERENCES `mydb`.`Publicacion` (`id_publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Intercambio_has_Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Intercambio_has_Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Intercambio_has_Usuario` (
  `Intercambio_id` INT NOT NULL,
  `Usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`Intercambio_id`, `Usuario_id_usuario`),
  INDEX `fk_Intercambio_has_Usuario_Usuario1_idx` (`Usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_Intercambio_has_Usuario_Intercambio1_idx` (`Intercambio_id` ASC) VISIBLE,
  CONSTRAINT `fk_Intercambio_has_Usuario_Intercambio1`
    FOREIGN KEY (`Intercambio_id`)
    REFERENCES `mydb`.`Intercambio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Intercambio_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Denuncia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Denuncia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Denuncia` (
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `denunciante` INT NOT NULL,
  `denunciado` INT NOT NULL,
  `id_publicacion` INT NOT NULL,
  INDEX `fk_Denuncia_Publicacion1_idx` (`id_publicacion` ASC) VISIBLE,
  INDEX `fk_denunciado_idx` (`denunciante` ASC, `denunciado` ASC) VISIBLE,
  CONSTRAINT `fk_publicacion`
    FOREIGN KEY (`id_publicacion`)
    REFERENCES `mydb`.`Publicacion` (`id_publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_denunciado`
    FOREIGN KEY (`denunciante` , `denunciado`)
    REFERENCES `mydb`.`Usuario` (`id_usuario` , `id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_has_Publicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario_has_Publicacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario_has_Publicacion` (
  `Usuario_id_usuario` INT NOT NULL,
  `Publicacion_id_publicacion` INT NOT NULL,
  PRIMARY KEY (`Usuario_id_usuario`, `Publicacion_id_publicacion`),
  INDEX `fk_Usuario_has_Publicacion_Publicacion1_idx` (`Publicacion_id_publicacion` ASC) VISIBLE,
  INDEX `fk_Usuario_has_Publicacion_Usuario1_idx` (`Usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_Publicacion_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Publicacion_Publicacion1`
    FOREIGN KEY (`Publicacion_id_publicacion`)
    REFERENCES `mydb`.`Publicacion` (`id_publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
